homepage
VanessaAoki/youtube-project pull request #5
Opened 2020-10-22 20:11 UTC by VanessaAoki

2020-10-22 20:48 UTC, arslanbisharat requested changes
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet. You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

- [x] Please make your PR descriptive. Please add more details to it. Please refer to [link 1 ](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request)to learn how to create PR and Edit it and [link 2](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/) to how to make it descriptive.  

- [x] I cannot see anything from your project because  Your project looks like this. 
**Clone**

![chrome-capture (14)](https://user-images.githubusercontent.com/58504655/96927810-0afceb80-14d1-11eb-8543-5a37e67a018d.jpg)

The problem is that you have to use the proper path in the src attribute of your HTML tag. Please use `./path` .

- [x] Please have a look at the inline-comments. 

- [ ] Please make your Readme more descriptive by adding the proper links to your social media accounts and a live link to your project. You can add details about your project and also you can add how to clone this project and acknowledgments. This [blog ](https://blog.bitsrc.io/how-to-write-beautiful-and-meaningful-readme-md-for-your-next-project-897045e3f991?gi=bddbb8c7067e)might help you. 

- [ ] Please move images from the sidebar folder to the images folder and then move the images folder and styled.css to one folder so that your repo looks clean. 


**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-10-22 20:48 UTC, arslanbisharat commented on styled.css
> +    margin: 0px;
Values of 0 shouldn't have units specified.

2020-10-22 20:48 UTC, arslanbisharat commented on styled.css
> +    padding-left: 0px;
Values of 0 shouldn't have units specified.

2020-10-22 20:48 UTC, arslanbisharat commented on index.html
> +            <img class="logo" src="/images/logo.png">
An img element must have an alt attribute

2020-10-22 20:48 UTC, arslanbisharat commented on index.html
> +            <img class="upload" src="/images/upload.png">
An img element must have an alt attribute

2020-10-22 20:48 UTC, arslanbisharat commented on index.html
> +                <img class="search-img" src="/images/search-icon.png">
An img element must have an alt attribute

2020-10-22 20:48 UTC, arslanbisharat commented on index.html
> +                    <img class="avatar2" src="/images/avatar2.png">
An img element must have an alt attribute

2020-10-22 20:48 UTC, arslanbisharat commented on index.html
> +                    <img class="more" src="images/More.png">
An img element must have an alt attribute

2020-10-22 20:48 UTC, arslanbisharat commented on index.html
> +                        <img src="/images/dislike.png">
An img element must have an alt attribute

2020-10-22 20:48 UTC, arslanbisharat commented on index.html
> +                    <img class="recommended-video" src="/sidebar/Contributiong to Open Source PartII: The Real Way.jpeg">
An img element must have an alt attribute

2020-10-22 20:48 UTC, arslanbisharat commented on index.html
> +                    <img class="recommended-video" src="/sidebar/Contributiong to Open Source PartII: The Real Way.jpeg">
An img element must have an alt attribute

2020-10-22 20:48 UTC, arslanbisharat commented on index.html
> +                    <img class="recommended-video" src="/sidebar/Contributiong to Open Source PartII: The Real Way.jpeg">
An img element must have an alt attribute

2020-10-22 20:48 UTC, arslanbisharat commented on index.html
> +                    <img class="recommended-video" src="/sidebar/Contributiong to Open Source PartII: The Real Way.jpeg">
An img element must have an alt attribute

2020-10-22 20:48 UTC, arslanbisharat commented on index.html
> +                    <img class="recommended-video" src="/sidebar/Contributiong to Open Source PartII: The Real Way.jpeg">
An img element must have an alt attribute

2020-10-22 20:48 UTC, arslanbisharat commented on index.html
> +    </div>
Stray end tag div

2020-10-22 20:48 UTC, arslanbisharat commented on index.html
> +            <img class="logo" src="/images/logo.png">
path should be src="./images/logo.png"

2020-10-22 20:48 UTC, arslanbisharat commented on index.html
> +                <img class="search-img" src="/images/search-icon.png">
the path should be `./images/search-icon.png`

2020-10-22 21:41 UTC, arslanbisharat requested changes
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet. You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

- [x] Your PR is not descriptive. Here is a suggestion. 
```

We made a clone of the youtube player page, it has a functional video, buttons, and interactive icons. The page works best on a 1366x768 resolution and using the firefox browser, assets might look out of place using other browsers or resolutions. It has mock suggestions showing video name and views, and a mock section for commentaries.

The focus of this branch was to make everything fit in their right places, along with a functional youtube video player.
```

- [x] Please make your Readme descriptive without mistakes. I have added some suggestions below. 

- [ ] Please remove spacing from the side of your page.

**Clone**

![chrome-capture (15)](https://user-images.githubusercontent.com/58504655/96932401-40f19e00-14d8-11eb-8053-b5bfc021987e.jpg)

- [x] Hamburger is missing. 

**Clone**

![chrome-capture (16)](https://user-images.githubusercontent.com/58504655/96932474-61b9f380-14d8-11eb-9646-b02d2bd1a5db.jpg)

- [ ] There should three icons and one avatar. But you have two icons and one avatar. 

![chrome-capture (17)](https://user-images.githubusercontent.com/58504655/96932550-7d24fe80-14d8-11eb-839a-7ca450147bc4.jpg)

- [ ] No item in this section is clickable. Please make the subscribe button and the rest of the items' proper link. 

![chrome-capture (18)](https://user-images.githubusercontent.com/58504655/96932737-ca08d500-14d8-11eb-8cff-f0405bd3f4b3.jpg)

- [ ] Autoplay button is missing here. 

**Clone**

![chrome-capture (19)](https://user-images.githubusercontent.com/58504655/96932809-e73da380-14d8-11eb-80a4-3e56f784044e.jpg)

- [ ] [Optioanl] It's good to have Comment section too. 


**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-10-22 21:41 UTC, arslanbisharat commented on README.md
> +> This project consists of building an HTML document that matches the appearance of youtube video player page.
**Change it to:** This project consists of building an HTML document that matches the appearance of the [youtube video player page](http://archive.vn/Bss88).

2020-10-22 21:41 UTC, arslanbisharat commented on README.md
> +Additional description about the project and its features.
Please remove this line or add description and features

2020-10-22 21:41 UTC, arslanbisharat commented on README.md
> +git clone https://github.com/elberthcorniell/Youtube-Clone.git
**Please change it to** https://github.com/VanessaAoki/youtube-project

2020-10-22 21:41 UTC, arslanbisharat commented on README.md
> +- GitHub: [@angelacuahutle](https://github.com/angelacuahutle)
Please add more social links like Linkedin Twitter etc.

2020-10-22 21:41 UTC, arslanbisharat commented on README.md
> +Feel free to check the [issues page](issues/).
Please add a proper issue page.

2020-10-22 21:41 UTC, arslanbisharat commented on README.md
> +This project is [MIT](https://github.com/elberthcorniell/Youtube-Clone/blob/video-frame/LICENSE.md) licensed.
Please add your own License

2020-10-23 22:26 UTC, mimipeshy commented
**STATUS : APPROVED :partying_face:  :tada:** 

Congratulations @VanessaAoki and @angelacuahutle  on working so hard on this project. It is approved !!!! I wish you all the best ahead in your coding journey. Cheers

Regards
Peris Ndanu

2020-10-26 14:58 UTC, merged